### PR TITLE
fix: import schema files to support bundlers

### LINKED ISSUE #2: Bundling with Webpack / Rollup / Parcel
When bundling with webpack, the `/schemas` directory tends to get left behind. Depending on the bundle, there's no easy way to include those files in the build every time because they're being loaded via `fs`. This is especially tricky on a serverless environment (AWS, etc). 

Alternatives to the current method could include making those files actual ts or js files and using `await import` to dynamically import the schema that's needed.

### PR DESCRIPTION
**Pull request by shellscape**
This PR changes the `/schemas` files to export a string. This directly supports use in bundlers following the precedent set by `node-xml-encryption`.  This fixes #2.

@tngan I would be happy to pay a bounty to get this update merged and published.

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -2,29 +2,21 @@ import * as mod from 'node-xmllint';
 import * as path from 'path';
```
Comment (tngan) [inline index.ts]:
```suggestion
```

File: index.ts [hunk 2]
```diff
@@ -2,29 +2,21 @@ import * as mod from 'node-xmllint';
...
 import * as fs from 'fs';
```
Comment (tngan) [inline index.ts]:
```suggestion
```

**Review by tngan — CHANGES_REQUESTED** [review]
There are two imports which are no longer to be used.

**Comment by tngan** [comment]
@shellscape Interesting, it would serve both serverless and with-server architecture. Good work.

With this change, I will bump a major version for it, just in case if there is potential side effect that we miss. I will do it right after this ticket is being merged.

**Comment by shellscape** [comment]
@tngan Done!

**Comment by shellscape** [comment]
Thank you!
